### ISSUE TITLE
connect_app : hmac.new(app_token.encode(), challenge, 'sha1')

### ISSUE THREAD

**Issue by afer92** [herrersystem/fbxtools#2]
Dans le calcul du hash, la chaîne 'sha1' est en anomalie.

Proposition de correction : 

from hashlib import sha1
hmac.new(app_token.encode(), challenge, sha1)

**Comment by herrersystem** [comment]
Ne touche que python 2.x. Je vais expliciter dans le readme (déjà explicité dans le setup.py) que ce module n'est pas développé pour la branche 2 de python.
